### ISSUE TITLE
Allow to set global config of axios

### ISSUE THREAD

**Issue by DalderupMaurice** [jeroenptrs/react-ion-store#10]
## Describe the solution you'd like and the expected behavior
Being able to configure the axios global config.
For ex: be able to set the baseurl or Authorization headers

## Is your feature request related to a problem? Please describe.
Yes, changing from dev to test/prod environment you have to change the base urls in every withCall call

## Possible implementation / References
/
## Additional context
/

**Comment by jeroenptrs** [comment]
YES! Thanks 😄
